# foo

development:
  adapter:  postgresql
  encoding: unicode
  database: meta_types_demo_dev
  pool:     5
  username: hornp
  password:

test:
  adapter:  postgresql
  encoding: unicode
  database: meta_types_demo_test
  pool:     5
  username: hornp
  password:

production:
  adapter:  postgresql
  encoding: unicode
  database: meta_types_demo_prod
  pool:     5
  username: hornp
  password:
